- platform: speedtest 
  monitored_conditions:
    - download
  minute:
    - 1

- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - summary
    - apparent_temperature

- platform: systemmonitor
  name: pi_status
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: /mnt
    - type: memory_use_percent
    - type: since_last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: process
      arg: transmission-daemon
    - type: process
      arg: Plex Media Server
    - type: process
      arg: pure-ftpd
    - type: process
      arg: openvpn
    - type: process
      arg: homebridge

- platform: template
  sensors:
    fibaro_office_battery_level:
      unit_of_measurement: '%'
      value_template: "{{ states.zwave.office_motion.attributes.battery_level | default(0) | int }}"
      icon_template: >
        {% set battery_level = states.zwave.office_motion.attributes.battery_level | default(0) | int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    fibaro_thomas_battery_level:
      unit_of_measurement: '%'
      value_template: "{{ states.zwave.thomas.attributes.battery_level  | default(0) | int  }}"
      icon_template: >
        {% set battery_level = states.zwave.thomas.attributes.battery_level | default(0) | int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    template_last_motion:
      friendly_name: 'Last Motion'
      value_template: >
        {%- set sensors = [states.binary_sensor.office_motion_sensor, states.binary_sensor.thomas_sensor] %}
        {% for sensor in sensors %}
          {% if as_timestamp(sensor.last_changed) == as_timestamp(sensors | map(attribute='last_changed') | max) %}
            {{ sensor.name }}
          {% endif %}
        {% endfor %}


- platform: pi_hole
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - unique_clients

- platform: command_line
  name: Last Backup
  command: "cat /home/homeassistant/.homeassistant/lastbackup.txt"
